const districtMap = {
   1: [
      'bolesławiecki',
      'głogowski',
      'jaworski',
      'kamiennogórski',
      'karkonoski',
      'legnicki',
      'lubański',
      'lubiński',
      'lwówecki',
      'polkowicki',
      'zgorzelecki',
      'złotoryjski',
      'Jelenia Góra',
      'Legnica',
   ],
   2: ['dzierżoniowski', 'kłodzki', 'świdnicki', 'wałbrzyski', 'ząbkowicki', 'Wałbrzych'],
   3: [
      'górowski',
      'milicki',
      'oleśnicki',
      'oławski',
      'strzeliński',
      'średzki',
      'trzebnicki',
      'wołowski',
      'wrocławski',
      'Wrocław',
   ],
   4: [
      'bydgoski',
      'inowrocławski',
      'mogileński',
      'nakielski',
      'sępoleński',
      'świecki',
      'tucholski',
      'żniński',
      'Bydgoszcz',
   ],
   5: [
      'aleksandrowski',
      'brodnicki',
      'chełmiński',
      'golubsko-dobrzyński',
      'grudziądzki',
      'lipnowski',
      'radziejowski',
      'rypiński',
      'toruński',
      'wąbrzeski',
      'włocławski',
      'Grudziądz',
      'Toruń',
      'Włocławek',
   ],
   6: [
      'janowski',
      'kraśnicki',
      'lubartowski',
      'lubelski',
      'łęczyński',
      'łukowski',
      'opolski',
      'puławski',
      'rycki',
      'świdnicki',
      'Lublin',
   ],
   7: [
      'bialski',
      'biłgorajski',
      'chełmski',
      'hrubieszowski',
      'krasnostawski',
      'parczewski',
      'radzyński',
      'tomaszowski',
      'włodawski',
      'zamojski',
      'Biała Podlaska',
      'Chełm',
      'Zamość',
   ],
   8: [],
   9: ['brzeziński', 'łódzki wschodni', 'Łódź'],
   10: [
      'bełchatowski',
      'opoczyński',
      'piotrkowski',
      'radomszczański',
      'rawski',
      'skierniewicki',
      'tomaszowski',
      'Piotrków Trybunalski',
      'Skierniewice',
   ],
   11: [
      'kutnowski',
      'łaski',
      'łęczycki',
      'łowicki',
      'pabianicki',
      'pajęczański',
      'poddębicki',
      'sieradzki',
      'wieluński',
      'wieruszowski',
      'zduńskowolski',
      'zgierski',
   ],
   12: ['chrzanowski', 'myślenicki', 'oświęcimski', 'suski', 'wadowicki'],
   13: ['krakowski', 'miechowski', 'olkuski', 'Kraków'],
   14: ['gorlicki', 'limanowski', 'nowosądecki', 'nowotarski', 'tatrzański', 'Nowy Sącz'],
   15: ['bocheński', 'brzeski', 'dąbrowski', 'proszowicki', 'tarnowski', 'wielicki', 'Tarnów'],
   16: [
      'ciechanowski',
      'gostyniński',
      'mławski',
      'płocki',
      'płoński',
      'przasnyski',
      'sierpecki',
      'sochaczewski',
      'żuromiński',
      'żyrardowski',
      'Płock',
   ],
   17: [
      'białobrzeski',
      'grójecki',
      'kozienicki',
      'lipski',
      'przysuski',
      'radomski',
      'szydłowiecki',
      'zwoleński',
      'Radom',
   ],
   18: [
      'garwoliński',
      'łosicki',
      'makowski',
      'miński',
      'ostrołęcki',
      'ostrowski',
      'pułtuski',
      'siedlecki',
      'sokołowski',
      'węgrowski',
      'wyszkowski',
      'Ostrołęka',
      'Siedlce',
   ],
   19: ['Warszawa'],
   20: [
      'grodziski',
      'legionowski',
      'nowodworski',
      'otwocki',
      'piaseczyński',
      'pruszkowski',
      'warszawski zachodni',
      'wołomiński',
   ],
   21: [],
   22: [
      'bieszczadzki',
      'brzozowski',
      'jarosławski',
      'jasielski',
      'krośnieński',
      'leski',
      'lubaczowski',
      'przemyski',
      'przeworski',
      'sanocki',
      'Krosno',
      'Przemyśl',
   ],
   23: [
      'dębicki',
      'kolbuszowski',
      'leżajski',
      'łańcucki',
      'mielecki',
      'niżański',
      'ropczycko-sędziszowski',
      'rzeszowski',
      'stalowowolski',
      'strzyżowski',
      'tarnobrzeski',
      'Rzeszów',
      'Tarnobrzeg',
   ],
   24: [],
   25: [
      'gdański',
      'kwidzyński',
      'malborski',
      'nowodworski',
      'starogardzki',
      'sztumski',
      'tczewski',
      'Gdańsk',
      'Sopot',
   ],
   26: [
      'bytowski',
      'chojnicki',
      'człuchowski',
      'kartuski',
      'kościerski',
      'lęborski',
      'pucki',
      'słupski',
      'wejherowski',
      'Gdynia',
      'Słupsk',
   ],
   27: ['bielski', 'cieszyński', 'pszczyński', 'żywiecki', 'Bielsko-Biała'],
   28: ['częstochowski', 'kłobucki', 'lubliniecki', 'myszkowski', 'Częstochowa'],
   29: ['gliwicki', 'tarnogórski', 'Bytom', 'Gliwice', 'Zabrze'],
   30: [
      'mikołowski',
      'raciborski',
      'rybnicki',
      'wodzisławski',
      'Jastrzębie-Zdrój',
      'Rybnik',
      'Żory',
   ],
   31: [
      'bieruńsko-lędziński',
      'Chorzów',
      'Katowice',
      'Mysłowice',
      'Piekary Śląskie',
      'Ruda Śląska',
      'Siemianowice Śląskie',
      'Świętochłowice',
      'Tychy',
   ],
   32: ['będziński', 'zawierciański', 'Dąbrowa Górnicza', 'Jaworzno', 'Sosnowiec'],
   33: [],
   34: [
      'bartoszycki',
      'braniewski',
      'działdowski',
      'elbląski',
      'iławski',
      'lidzbarski',
      'nowomiejski',
      'ostródzki',
      'Elbląg',
   ],
   35: [
      'ełcki',
      'giżycki',
      'gołdapski',
      'kętrzyński',
      'mrągowski',
      'nidzicki',
      'olecki',
      'olsztyński',
      'piski',
      'szczycieński',
      'węgorzewski',
      'Olsztyn',
   ],
   36: [
      'gostyński',
      'jarociński',
      'kaliski',
      'kępiński',
      'kościański',
      'krotoszyński',
      'leszczyński',
      'ostrowski',
      'ostrzeszowski',
      'pleszewski',
      'rawicki',
      'Kalisz',
      'Leszno',
   ],
   37: [
      'gnieźnieński',
      'kolski',
      'koniński',
      'słupecki',
      'średzki',
      'śremski',
      'turecki',
      'wrzesiński',
      'Konin',
   ],
   38: [
      'chodzieski',
      'czarnkowsko-trzcianecki',
      'grodziski',
      'międzychodzki',
      'nowotomyski',
      'obornicki',
      'pilski',
      'szamotulski',
      'wągrowiecki',
      'wolsztyński',
      'złotowski',
   ],
   39: ['poznański', 'Poznań'],
   40: [
      'białogardzki',
      'choszczeński',
      'drawski',
      'kołobrzeski',
      'koszaliński',
      'sławieński',
      'szczecinecki',
      'świdwiński',
      'wałecki',
      'Koszalin',
   ],
   41: [
      'goleniowski',
      'gryficki',
      'gryfiński',
      'kamieński',
      'łobeski',
      'myśliborski',
      'policki',
      'pyrzycki',
      'stargardzki',
      'Szczecin',
      'Świnoujście',
   ],
}
