import { useEffect, useState, useRef } from 'react'
import CircuitMap from '@/components/map/circuit-map'
import Head from 'next/head'
import Navbar from '@/components/navbar/navbar'
import CircuitCard from '@/components/circuit/circuit-card'
import TripPlanner from '@/components/trip/trip-planner'

export default function Home() {
   const [circuits, setCircuits] = useState<Circuit[]>()
   const [selectedCircuit, setSelectedCircuit] = useState<Circuit | undefined>()
   const [scoredCircuits, setScoredCircuits] = useState<ScoredCircuit[] | undefined>()
   const tripCount = 3 // how many top trips to show on List and Map

   useEffect(() => {
      fetch('/api/get-circuits')
         .then((res) => res.json())
         .then((circuits) => {
            if (circuits) {
               console.log(circuits)
               setCircuits(circuits)
            }
         })
      // eslint-disable-next-line react-hooks/exhaustive-deps
   }, [])

   useEffect(() => {
      console.log(selectedCircuit)
   }, [selectedCircuit])

   const selectCircuit = (circuit: Circuit) => {
      // setSelectedCircuit(circuit)
      planTrip(circuit)
   }

   const planTrip = (circuit: Circuit) => {
      const { city_name } = circuit
      console.log('Planning a trip from', city_name)

      const payload = {
         selectedCircuit: circuit,
         circuits: circuits,
      }

      fetch('/api/get-scored-circuits', {
         method: 'POST',
         body: JSON.stringify(payload),
         headers: {
            'Content-Type': 'application/json',
         },
      })
         .then((res) => res.json())
         .then((scoredCircuits) => {
            if (scoredCircuits) {
               console.log('[get-scored-circuits]', scoredCircuits)
               setScoredCircuits(scoredCircuits)
               setSelectedCircuit(
                  scoredCircuits.find((scoredCircuit: ScoredCircuit) => {
                     if (scoredCircuit.city_id == circuit.city_id) {
                        return circuit
                     }
                  })
               )
            }
         })
   }

   return (
      <>
         <Head>
            <title>Vote Tripper</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <Navbar selectedCircuit={selectedCircuit} planTrip={planTrip} />

         <CircuitMap
            selectedCircuit={selectedCircuit}
            selectCircuit={selectCircuit} // handler
            circuitList={circuits}
            scoredCircuits={scoredCircuits}
            tripCount={tripCount}
         />
         {selectedCircuit && scoredCircuits && (
            <TripPlanner
               tripCount={tripCount}
               scoredCircuits={scoredCircuits}
               startCircuit={selectedCircuit}
            />
         )}
      </>
   )
}
